---
title: "CovidEM_figures"
author: "Zak"
date: "5/24/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls())

library(ggplot2)


```

Data input
```{r}

ci_in <- read.csv("~/NIH/CovidStratified/Output/CIEstimates2.csv")

ci <- ci_in
ci

ci2 <- data.frame(Age = ci$Age,
                  Lower = (ci$Estimate - ci$Lower), 
                  Upper = (ci$Estimate - ci$Upper)
ci2
```

Graphing
```{r}
p <- ggplot() +
    geom_errorbar(data = ci, aes(x = Age, ymin = Lower, ymax = Upper)) +
    geom_point(data = ci, aes(x = Age, y = Estimate), size = 1.5) +
    ggtitle("Estimates with 95% errors")
print(p)

p2 <- ggplot(data = ci2, aes(x = Age, ymin = Lower, ymax = Upper)) +
    geom_errorbar() +
    ggtitle("Centralized 95% errors")
print(p2)

p3 <- ggplot() +
    geom_errorbar(data = ci, aes(x = Age, ymin = Lower, ymax = Upper)) +
    geom_point(data = ci, aes(x = Age, y = Estimate), size = 1.5) +
    scale_y_continuous(trans = "log10") +
    ggtitle("Estimates with 95% errors\nLog 10 transformation")
print(p3)

```

